# Generated by Django 2.2.12 on 2020-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
